### ISSUE TITLE
Copyright 2021

### ISSUE THREAD

**Issue by HiddeKoerts** [Confluente/Angular-Frontend#47]
Update the copyright year in the footer to 2021

**Comment by 96RadhikaJadhav** [comment]
@HiddeKoerts Can I work on the issue?

**Comment by HiddeKoerts** [comment]
> @HiddeKoerts Can I work on the issue?

Are you in any way affiliated to the study association H.S.A. Confluente? Currently this is still an in-house project, even though our repos are set to public.

**Comment by 96RadhikaJadhav** [comment]
> > @HiddeKoerts Can I work on the issue?
> 
> Are you in any way affiliated to the study association H.S.A. Confluente? - No
Currently this is still an in-house project, even though our repos are set to public. - Okay, no problem. Thank You.
