### ISSUE TITLE
Make the 'link' on the 'honors room' page a normal size.

### ISSUE THREAD

**Issue by rdvhoorn** [Confluente/Angular-Frontend#50]
On [this](https://hsaconfluente.nl/about/HR) page there is a link to the TU/e website, but it spans like more than a line, and it looks ugly. Would be nice to change it such that it covers a 'normal' number of words.

**Comment by aditya28sarin** [comment]
can  you assign me this issue?

**Comment by 96RadhikaJadhav** [comment]
@rdvhoorn  Can I work on the issue?

**Comment by Jordi24** [comment]
Issue was solved and merged into master with #59.
