### ISSUE TITLE
Center text in div

### ISSUE THREAD

**Issue by rdvhoorn** [Confluente/Angular-Frontend#56]
If you hover over all [these squares](https://hsaconfluente.nl/partners/sister_associations), you see the name of sister associations. Would be nice if these names were centered in the div.

**Comment by aditya28sarin** [comment]
Can you assign me this issue?

**Comment by rdvhoorn** [comment]
Assigned you! I also invited you to the github organization :) If you join the organization, you can assign issues to yourself I think :)

**Comment by aditya28sarin** [comment]
I have made some changes but cannot run it locally for some reason, I will create a pull request can you just check and let me know

**Comment by rdvhoorn** [comment]
damn, already taking of haha, ill move the discussion not the pull request and link this issue to there

**Comment by vishal78689** [comment]
i can help you with this issue

**Comment by Jordi24** [comment]
Issue was solved and merged into master with #60.
